import type { Car } from "@/types/car";

export const MOCK_CARS: Car[] = [
  {
    id: "1",
    brand: "Volkswagen",
    model: "Polo",
    version: "1.0 TSI Comfortline",
    year: 2024,
    price: 92_900,
    km: 12_500,
    condition: "usado",
    fuel: "flex",
    color: "branco",
    doors: 4,
    plateEnd: 3,
    features: [
      "ar-condicionado",
      "direcao-eletrica",
      "cambio-automatico",
      "abs",
      "airbag",
      "multimidia",
      "vidros-eletricos",
    ],
  },
  {
    id: "2",
    brand: "Chevrolet",
    model: "Onix",
    version: "1.0 Turbo LTZ",
    year: 2025,
    price: 105_500,
    km: 0,
    condition: "novo",
    fuel: "flex",
    color: "prata",
    doors: 4,
    plateEnd: 7,
    features: [
      "ar-condicionado",
      "direcao-eletrica",
      "cambio-automatico",
      "abs",
      "airbag",
      "multimidia",
      "camera-re",
      "vidros-eletricos",
    ],
  },
  {
    id: "3",
    brand: "Fiat",
    model: "Mobi",
    version: "1.0 Like",
    year: 2022,
    price: 58_900,
    km: 38_700,
    condition: "usado",
    fuel: "flex",
    color: "vermelho",
    doors: 4,
    plateEnd: 1,
    features: ["ar-condicionado", "direcao-eletrica", "abs", "airbag"],
  },
  {
    id: "4",
    brand: "Toyota",
    model: "Corolla",
    version: "2.0 XEi",
    year: 2023,
    price: 162_000,
    km: 24_900,
    condition: "usado",
    fuel: "flex",
    color: "preto",
    doors: 4,
    plateEnd: 5,
    features: [
      "ar-condicionado",
      "direcao-eletrica",
      "cambio-automatico",
      "abs",
      "airbag",
      "multimidia",
      "sensor-re",
      "camera-re",
      "vidros-eletricos",
    ],
  },
  {
    id: "5",
    brand: "Honda",
    model: "HR-V",
    version: "1.5 Touring CVT",
    year: 2025,
    price: 198_900,
    km: 0,
    condition: "novo",
    fuel: "flex",
    color: "cinza",
    doors: 4,
    plateEnd: 9,
    features: [
      "ar-condicionado",
      "direcao-eletrica",
      "cambio-automatico",
      "abs",
      "airbag",
      "multimidia",
      "sensor-re",
      "camera-re",
      "vidros-eletricos",
    ],
  },
  {
    id: "6",
    brand: "Jeep",
    model: "Compass",
    version: "T270 Limited",
    year: 2024,
    price: 215_500,
    km: 18_300,
    condition: "usado",
    fuel: "flex",
    color: "azul",
    doors: 4,
    plateEnd: 2,
    features: [
      "ar-condicionado",
      "direcao-eletrica",
      "cambio-automatico",
      "abs",
      "airbag",
      "multimidia",
      "sensor-re",
      "camera-re",
      "vidros-eletricos",
    ],
  },
  {
    id: "7",
    brand: "Hyundai",
    model: "HB20",
    version: "1.0 Comfort",
    year: 2021,
    price: 64_900,
    km: 52_400,
    condition: "usado",
    fuel: "flex",
    color: "branco",
    doors: 4,
    plateEnd: 0,
    features: ["ar-condicionado", "direcao-eletrica", "abs", "airbag", "vidros-eletricos"],
  },
  {
    id: "8",
    brand: "Ford",
    model: "Ranger",
    version: "3.0 V6 Limited 4x4",
    year: 2025,
    price: 389_900,
    km: 0,
    condition: "novo",
    fuel: "diesel",
    color: "preto",
    doors: 4,
    plateEnd: 8,
    features: [
      "ar-condicionado",
      "direcao-eletrica",
      "cambio-automatico",
      "abs",
      "airbag",
      "multimidia",
      "sensor-re",
      "camera-re",
      "vidros-eletricos",
    ],
  },
  {
    id: "9",
    brand: "Renault",
    model: "Kwid",
    version: "1.0 Zen",
    year: 2023,
    price: 62_500,
    km: 28_100,
    condition: "usado",
    fuel: "flex",
    color: "amarelo",
    doors: 4,
    plateEnd: 4,
    features: ["ar-condicionado", "direcao-eletrica", "abs", "airbag"],
  },
  {
    id: "10",
    brand: "Toyota",
    model: "Yaris",
    version: "1.5 XS Sedan",
    year: 2022,
    price: 89_700,
    km: 41_800,
    condition: "usado",
    fuel: "flex",
    color: "prata",
    doors: 4,
    plateEnd: 6,
    features: [
      "ar-condicionado",
      "direcao-eletrica",
      "cambio-automatico",
      "abs",
      "airbag",
      "multimidia",
      "vidros-eletricos",
    ],
  },
  {
    id: "11",
    brand: "Volkswagen",
    model: "T-Cross",
    version: "1.4 TSI Highline",
    year: 2024,
    price: 159_900,
    km: 9_800,
    condition: "usado",
    fuel: "flex",
    color: "verde",
    doors: 4,
    plateEnd: 7,
    features: [
      "ar-condicionado",
      "direcao-eletrica",
      "cambio-automatico",
      "abs",
      "airbag",
      "multimidia",
      "sensor-re",
      "camera-re",
      "vidros-eletricos",
    ],
  },
  {
    id: "12",
    brand: "Fiat",
    model: "Fiorino",
    version: "1.4 Endurance",
    year: 2018,
    price: 49_900,
    km: 110_500,
    condition: "usado",
    fuel: "flex",
    color: "branco",
    doors: 2,
    plateEnd: 1,
    features: ["ar-condicionado", "abs", "airbag"],
  },
  {
    id: "13",
    brand: "Hyundai",
    model: "Creta",
    version: "1.0 Turbo Comfort",
    year: 2024,
    price: 134_500,
    km: 15_600,
    condition: "usado",
    fuel: "flex",
    color: "azul",
    doors: 4,
    plateEnd: 5,
    features: [
      "ar-condicionado",
      "direcao-eletrica",
      "cambio-automatico",
      "abs",
      "airbag",
      "multimidia",
      "camera-re",
      "vidros-eletricos",
    ],
  },
  {
    id: "14",
    brand: "Chevrolet",
    model: "S10",
    version: "2.8 LTZ 4x4",
    year: 2020,
    price: 215_000,
    km: 78_900,
    condition: "usado",
    fuel: "diesel",
    color: "cinza",
    doors: 4,
    plateEnd: 9,
    features: [
      "ar-condicionado",
      "direcao-eletrica",
      "cambio-automatico",
      "abs",
      "airbag",
      "multimidia",
      "sensor-re",
      "vidros-eletricos",
    ],
  },
];
